spring.application.name=ITK-tasks-SpringSecurity

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:SpringData-2-projections
spring.datasource.username=user
spring.datasource.password=123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=secret_key_secret_key_secret_key_secret_key_
jwt.expiration.hour_in_ms=3600000
jwt.expiration.hour_multiplier=24
